---
name: Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setup pnpm
        run: sudo npm i -g pnpm@8.15.1
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: ESLINT
        run: pnpm lint
      - name: Vitest
        run: pnpm run -C packages/sdk test
